Files and folders restructure
DankMemer/dankmemer.lol pull request #39
Opened 2020-12-01 05:36 UTC by InBlue

I restructured all the folders to make them a little cleaner.
Some of the pages may not load correctly as I have no checked all of them as I cannot access them

I was unable to check the following
- Admin pages
- Some payment pages
- Landing
- Appeals
- Reports
- Rules

I plan on converting all the files to functional components sometime but will leave it for now.

2020-12-01 21:58 UTC, aetheryx approved these changes

2020-12-01 22:56 UTC, melmsie requested changes
Appeals page is the only one that doesn't work for me.

2020-12-01 23:15 UTC, InBlue commented
Putting the footer outside the pseudoBody element seemed to fix the position when loading the page. The worst it was when I tested was at the bottom of the viewbox when no content had loaded.

2020-12-02 14:56 UTC, melmsie approved these changes

2020-12-02 14:56 UTC, merged